web:
  build: .
  volumes:
    - .:/robot_sim
  ports:
    - "3000:3000"
  # links:
    # - db
    # - mailcatcher
  # env_file:
  #   - '.env.web'
  command: bash -c "rm -rf tmp/* && ruby robot_simulator_test.rb"
